In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [6]:
"""
 Pandas Dataframe : A data structure for tabular data
"""
health_data_table={
    "height":[5.5,5.5,'A',5.8],
    "weight":[57,62,72,75],
    "bmi":[19.3,12.7,20.3,None],
    'smoker':['Yes','no',None,'Yes']
}

In [7]:
health_data_table.keys()

dict_keys(['height', 'weight', 'bmi', 'smoker'])

In [8]:
health_data_table.values()

dict_values([[5.5, 5.5, 'A', 5.8], [57, 62, 72, 75], [19.3, 12.7, 20.3, None], ['Yes', 'no', None, 'Yes']])

In [9]:
health_data_frame=pd.DataFrame(health_data_table)

In [11]:
health_data_frame.head(2)

  height  weight   bmi smoker
0    5.5      57  19.3    Yes
1    5.5      62  12.7     no

In [13]:
health_data_frame.tail(3)

  height  weight   bmi smoker
1    5.5      62  12.7     no
2      A      72  20.3    NaN
3    5.8      75   NaN    Yes

In [15]:
health_data_frame.shape

(4, 4)

In [16]:
health_data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  4 non-null      object
 1   weight  4 non-null      int64
 2   bmi     3 non-null      float64
 3   smoker  3 non-null      str
dtypes: float64(1), int64(1), object(1), str(1)
memory usage: 260.0+ bytes

In [17]:
# Statistical Summary
health_data_frame.describe()

         weight        bmi
count   4.00000   3.000000
mean   66.50000  17.433333
std     8.42615   4.129568
min    57.00000  12.700000
25%    60.75000  16.000000
50%    67.00000  19.300000
75%    72.75000  19.800000
max    75.00000  20.300000

In [20]:
health_data_np_array=health_data_frame.values
print(health_data_np_array)
print(type(health_data_np_array))

[[5.5 57 19.3 'Yes']
 [5.5 62 12.7 'no']
 ['A' 72 20.3 nan]
 [5.8 75 nan 'Yes']]
<class 'numpy.ndarray'>

In [24]:
print(health_data_frame.columns)
print(type(health_data_frame.columns))

Index(['height', 'weight', 'bmi', 'smoker'], dtype='str')
<class 'pandas.Index'>